{{- if .Values.acme.http01.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.http01.name }}
spec:
  acme:
    server: {{.Values.acme.url}}
    email: {{.Values.acme.registrationEmail}}
    privateKeySecretRef:
      name: letsencrypt-http01
    solvers:
      - http01:
          ingress:
            ingressClassName: {{.Values.acme.http01.ingressClassName}}
{{- end }}
