{{- if .Values.acme.dns01.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    email: {{ .Values.acme.registrationEmail }}
    server: {{ .Values.acme.url }}
    privateKeySecretRef:
      name: letsencrypt-dns01
    solvers:
      - dns01:
{{ toYaml .Values.acme.dns01.solver | indent 10 }}
{{- end }}
