{{- if .Values.acme.dns01.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.dns01.name }}
spec:
  acme:
    email: {{ .Values.acme.registrationEmail }}
    server: {{ .Values.acme.url }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.default.name }}
    solvers:
      - dns01:
{{ toYaml .Values.acme.dns01.solver | indent 10 }}
{{- end }}
