---
apiVersion: kro.run/v1alpha1
kind: BootstrapConfig
metadata:
  name: {{ .Values.name }}-{{ .Values.namespace }}-bootstrap-config
spec:
  machineDeployment:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
