acme:
  url: undefined
  registrationEmail: undefined
  dns01:
    enabled: true
    solver:
      webhook:
        groupName: undefined
        solverName: undefined
        config:
          authTokenSecretNamespace: undefined
          projectId: undefined
