{{- $domains := fromJson .Values.certificate.dnsNames }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: Issuer
  renewBefore: {{ .Values.certificate.renewBefore }}
  dnsNames: 
  {{- range $domains }}
    - {{ . | quote}}
  {{- end }}
