apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: stackit-letsencrypt-dns01
    kind: Issuer
  renewBefore: {{ .Values.certificate.renewBefore }}
  dnsNames: {{ .Values.certificate.dnsNames }}
