apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
spec:
  secretName: ingress-nginx-admission
  duration: 8760h  # 1 year
  renewBefore: 360h
  dnsNames:
    - ingress-nginx-controller-admission
    - ingress-nginx-controller-admission.ingress-nginx
    - ingress-nginx-controller-admission.ingress-nginx.svc
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
