apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: stackit-cluster-secret-store
spec:
  provider:
    vault:
      server: https://prod.sm.eu01.stackit.cloud
      path: {{ .Values.stackit.sm_secret_instance_id }}
      version: v2
      auth:
        userPass:
          path: userpass
          username: {{ .Values.stackit.sm_user }}
          secretRef:
            name: {{ .Values.stackit.sm_secret_name }}
            namespace: {{ .Values.stackit.sm_secret_namespace }}
            key: password

