apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stackit-cert-manager-webhook
  namespace: {{ .Values.secret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: stackit-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: stackit-cert-manager-webhook
    creationPolicy: Owner
  data:
    - secretKey: auth-token
      remoteRef:
        key: {{ .Values.secret.cert_manager_stackit_webhook_service_account_secret }}
        property: token
