apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stackit-sa-authentication
  namespace: {{ .Values.secret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: stackit-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: stackit-sa-authentication
    creationPolicy: Owner
  data:
    - secretKey: sa.json
      remoteRef:
        key: {{ .Values.secret.cert_manager_stackit_webhook_service_account_secret }}
        property: key_json
