apiVersion: v1
data:
  auth-token: {{ .Values.secret.data.service_account_token | b64enc | quote }}
kind: Secret
metadata:
  name: stackit-cert-manager-webhook
  namespace: {{ .Values.secret.namespace }}
